/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/Blender/dolphin.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dolphin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tmp37gbq0itply_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.tmp37gbq0itply_2.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/dolphin.glb')
